### ISSUE TITLE
Mountain Lion not working

### ISSUE THREAD

**Issue by Chip-McK** [ChaosCoder/Launchpad-Control#3]
Refresh does not result in the current LaunchPad "menus"

Apply  not not update the current 'menus"

**Comment by RoyiAvital** [comment]
Does it work with OS X 10.9 and 10.10?

**Comment by Chip-McK** [comment]
No,  it does not

**Comment by RoyiAvital** [comment]
Any chance to build something that would work in 10.9 and 10.10 to change the name of an applications?

**Comment by Chip-McK** [comment]
You should ask the author or suggest to Apple

**Comment by RoyiAvital** [comment]
Well,
You understand that when I write here I expect the author to answer, right?
